=== 0Hannes0/Labore/Lab2_Tobi/vorlesungsplan.dtd
<!ELEMENT vorlesungsplan (semester+)>
<!ATTLIST vorlesungsplan xmlns:uni CDATA #IMPLIED>

<!ELEMENT semester (kurs+)>
<!ATTLIST semester jahr CDATA #REQUIRED>
<!ATTLIST semester typ CDATA #REQUIRED>

<!ELEMENT kurs (veranstaltung+)>
<!ATTLIST kurs name CDATA #REQUIRED>

<!ELEMENT veranstaltung (titel, typ)>
<!ATTLIST veranstaltung dozent CDATA #REQUIRED>
<!ATTLIST veranstaltung raum CDATA #REQUIRED>
<!ATTLIST veranstaltung zeit CDATA #REQUIRED>

<!ELEMENT titel (#PCDATA)>
<!ELEMENT typ (#PCDATA)>

=== 0Hannes0/Labore/Lab2_Tobi/vorlesungsplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vorlesungsplan SYSTEM "vorlesungsplan.dtd">
<vorlesungsplan xmlns:uni="http://example.com/universitaet">
    <semester jahr="2025" typ="Sommersemester">
        <kurs name="Informatik 1">
            <veranstaltung dozent="Dr. Müller" raum="A101" zeit="08:00-09:30">
                <uni:titel>Einführung in XML</uni:titel>
                <typ>Vorlesung</typ>
            </veranstaltung>
            <veranstaltung dozent="Prof. Schmidt" raum="B202" zeit="10:00-11:30">
                <uni:titel>Datenbanken</uni:titel>
                <typ>Übung</typ>
            </veranstaltung>
        </kurs>
    </semester>
</vorlesungsplan>
